version: '3.6'

services:
  postgres-db:
    image: postgres:13
    build: .
    #  context: .
    #  dockerfile: pg-Dockerfile
    environment:
      POSTGRES_DB: remi-memory
      POSTGRES_USER: remi-user
      POSTGRES_PASSWORD: 123456
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 8197:5432
    container_name: postgres-remi
